kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: expense
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: alma
      image: almalinux:9
      command: ["sleep", "3600"]
