apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - name: secret-container
      image: almalinux:9
      command: ["sleep" , "3600"]
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: password