kind: Service
apiVersion: v1
metadata:
  name: nginx-nodeport
spec:
  type: NodePort # This will expose the service on a static port on each node in the cluster, allowing external access to the service.
  selector:
    app: nginx
    component: web
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
