kind: Service
apiVersion: v1
metadata:
  name: nginx-nodeport
spec:
  selector:
    app: nginx
    component: web
    environment: dev
    type: NodePort # Define the type of service (ClusterIP, NodePort, LoadBalancer)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
