kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: loadbalancer # This will create an external load balancer (if supported by the cloud provider) and expose the service to the internet.
  selector:
    app: nginx
    component: web
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # This is the port that will be exposed on each node. You can choose any port in the range 30000-32767
