apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    name: pod-1
    purpose: test-affinity
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always 
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    name: pod-2
    purpose: test-affinity-2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always 
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-3
  labels:
    name: pod-3
    purpose: test-affinity-3
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-1
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always 